/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import koneksi.conek;

/**
 *
 * @author imam
 */
public class laporanhasilpenjualan extends javax.swing.JFrame {

    /**
     * Creates new form laporanhasilpenjualan
     */
    public laporanhasilpenjualan() {
        initComponents();
        loadtahun();
    }
    public Connection con;
    private String sql;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement ps;
    private DefaultTableModel dtm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jctgl = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jctahun = new javax.swing.JComboBox<>();
        jctahunan = new javax.swing.JCheckBox();
        jcbulanan = new javax.swing.JCheckBox();
        jccariharian = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_record = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(49, 163, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "LAPORAN HASIL PENJUALAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel2.setBackground(new java.awt.Color(132, 196, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Form Input"));

        jctgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));

        jLabel1.setText("Tanggal");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel2.setText("Bulan");

        jLabel3.setText("Tahun");

        jctahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jctahunan.setText("Record Tahunan");

        jcbulanan.setText("Record Bulanan");

        jccariharian.setText("Record Perhari");
        jccariharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jccariharianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jctgl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jctahun, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jccariharian)
                        .addGap(18, 18, 18)
                        .addComponent(jcbulanan)
                        .addGap(18, 18, 18)
                        .addComponent(jctahunan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jctgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jctahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jccariharian)
                    .addComponent(jcbulanan)
                    .addComponent(jctahunan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(132, 196, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Navigasi"));

        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add_1.png"))); // NOI18N

        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OK.png"))); // NOI18N
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btncari)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambah)
                    .addComponent(btncari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(132, 196, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Tabel Hasil Penjualan"));

        tabel_record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_record);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jccariharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jccariharianMouseClicked
        // TODO add your handling code here:
        jctgl.setEnabled(true);
        jComboBox1.setEnabled(true);
        jctahun.setEnabled(true);
    }//GEN-LAST:event_jccariharianMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        if(jccariharian.isSelected()==true){
           
            //form_cari_harian();
            cariharian();
        } else if (jcbulanan.isSelected()==true){
            caribulanan();
        } else if(jctahunan.isSelected()==true){
            caritahunan();
        }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanhasilpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanhasilpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanhasilpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanhasilpenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanhasilpenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jcbulanan;
    private javax.swing.JCheckBox jccariharian;
    private javax.swing.JComboBox<String> jctahun;
    private javax.swing.JCheckBox jctahunan;
    private javax.swing.JComboBox<String> jctgl;
    private javax.swing.JTable tabel_record;
    // End of variables declaration//GEN-END:variables

    private void loadtahun() {
       //To change body of generated methods, choose Tools | Templates.
       try {        
        jctahun.removeAllItems();
        
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                    
        
            Statement s= con.createStatement();
           
            
            String sql="Select YEAR(tgl) as tahun from penjualan group by YEAR(tgl)";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                jctahun.addItem(r.getString("tahun"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
            JOptionPane.showMessageDialog(null, e.getMessage());
        } 
    }

    private void cariharian() {
        //To change body of generated methods, choose Tools | Templates.
         DefaultTableModel tabelpegawai = new DefaultTableModel();
       // tabelpegawai.addColumn("NO TRANSAKSI");
       tabelpegawai.addColumn("TANGGAL ");
        tabelpegawai.addColumn("TOTAL HARGA ");
        tabelpegawai.addColumn("TOTOAL DISKON");
        
         try {
            
           conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
      //  String sql = "select idmember, alamat from member where idmember like '%" + jtextcari.getText() + "%'" ;
     // String sql = "select penjualan.no_transaksi,barang.nama_barang,penjualan.jumlah,penjualan.total_harga from barang,penjualan where penjualan.id_barang = barang.id_barang";
   // String sql = "select member.idmember,diskon.potongan,diskon.jmlptg from member,diskon where member.tingkatan=diskon.tingkatan";
   // String sql = "select idmember, alamat from member where idmember like '%" + jtextcari.getText() + "%'" ;
   
   //String sql = "select member.idmember,member.nama, member.tingkatan, diskon.potongan,diskon.jmlptg from member,diskon where member.tingkatan=diskon.tingkatan AND member.idmember like '%"+ jtextcari.getText() + "%'";
        
  // String sql = "select penjualan.tgl ,penjualan.id_barang , barang.nama_barang , penjualan.jumlah , pembayaran.totalbeli , pembayaran.bayar , pembayaran.kembali , pembayaran.diskon from pembayaran,penjualan,barang where penjualan.tgl=pembayaran.tgl AND barang.id_barang=penjualan.id_barang  AND YEAR(pembayaran.tgl) = '" + jctahun.getSelectedItem()+ "'"  ;
  
  String sql = "SELECT tgl, SUM(totalbeli), SUM(diskon) FROM pembayaran WHERE DAY(tgl)='"+ jctgl.getSelectedItem()+"' AND MONTH(tgl)='"+jComboBox1.getSelectedItem()+  "'AND YEAR(tgl)= '"+jctahun.getSelectedItem()+"'";
  
   Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
            
           
            
            
            while (res.next()) {
                tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)});
            }
           tabel_record.setModel(tabelpegawai);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
                    
          
        }
        
    }

    private void caribulanan() {
        //To change body of generated methods, choose Tools | Templates.
          DefaultTableModel tabelpegawai = new DefaultTableModel();
       // tabelpegawai.addColumn("NO TRANSAKSI");
       tabelpegawai.addColumn("BULAN ");
        tabelpegawai.addColumn("TAHUN");
        tabelpegawai.addColumn("TOTAL HARGA ");
        tabelpegawai.addColumn("TOTOAL DISKON");
        
        
        
        
         try {
            
           conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
      //  String sql = "select idmember, alamat from member where idmember like '%" + jtextcari.getText() + "%'" ;
     // String sql = "select penjualan.no_transaksi,barang.nama_barang,penjualan.jumlah,penjualan.total_harga from barang,penjualan where penjualan.id_barang = barang.id_barang";
   // String sql = "select member.idmember,diskon.potongan,diskon.jmlptg from member,diskon where member.tingkatan=diskon.tingkatan";
   // String sql = "select idmember, alamat from member where idmember like '%" + jtextcari.getText() + "%'" ;
   
   //String sql = "select member.idmember,member.nama, member.tingkatan, diskon.potongan,diskon.jmlptg from member,diskon where member.tingkatan=diskon.tingkatan AND member.idmember like '%"+ jtextcari.getText() + "%'";
        
  // String sql = "select penjualan.tgl ,penjualan.id_barang , barang.nama_barang , penjualan.jumlah , pembayaran.totalbeli , pembayaran.bayar , pembayaran.kembali , pembayaran.diskon from pembayaran,penjualan,barang where penjualan.tgl=pembayaran.tgl AND barang.id_barang=penjualan.id_barang  AND YEAR(pembayaran.tgl) = '" + jctahun.getSelectedItem()+ "'"  ;
  
  String sql = "SELECT MONTH(tgl), YEAR(tgl), SUM(totalbeli), SUM(diskon) FROM pembayaran WHERE MONTH(tgl)='"+jComboBox1.getSelectedItem()+  "'AND YEAR(tgl)= '"+jctahun.getSelectedItem()+"'";
  
   Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
            
           
            
            
            while (res.next()) {
                tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
            }
           tabel_record.setModel(tabelpegawai);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
                    
          
        }
        
    }

    private void caritahunan() {
         //To change body of generated methods, choose Tools | Templates.
         
         DefaultTableModel tabelpegawai = new DefaultTableModel();
       // tabelpegawai.addColumn("NO TRANSAKSI");
       tabelpegawai.addColumn("TAHUN ");
        tabelpegawai.addColumn("TOTAL HARGA ");
        tabelpegawai.addColumn("TOTOAL DISKON");
        
        
        
        
         try {
            
           conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
      //  String sql = "select idmember, alamat from member where idmember like '%" + jtextcari.getText() + "%'" ;
     // String sql = "select penjualan.no_transaksi,barang.nama_barang,penjualan.jumlah,penjualan.total_harga from barang,penjualan where penjualan.id_barang = barang.id_barang";
   // String sql = "select member.idmember,diskon.potongan,diskon.jmlptg from member,diskon where member.tingkatan=diskon.tingkatan";
   // String sql = "select idmember, alamat from member where idmember like '%" + jtextcari.getText() + "%'" ;
   
   //String sql = "select member.idmember,member.nama, member.tingkatan, diskon.potongan,diskon.jmlptg from member,diskon where member.tingkatan=diskon.tingkatan AND member.idmember like '%"+ jtextcari.getText() + "%'";
        
  // String sql = "select penjualan.tgl ,penjualan.id_barang , barang.nama_barang , penjualan.jumlah , pembayaran.totalbeli , pembayaran.bayar , pembayaran.kembali , pembayaran.diskon from pembayaran,penjualan,barang where penjualan.tgl=pembayaran.tgl AND barang.id_barang=penjualan.id_barang  AND YEAR(pembayaran.tgl) = '" + jctahun.getSelectedItem()+ "'"  ;
  
  String sql = "SELECT YEAR(tgl), SUM(totalbeli), SUM(diskon) FROM pembayaran WHERE  YEAR(tgl)= '"+jctahun.getSelectedItem()+"'";
  
   Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
            
           
            
            
            while (res.next()) {
                tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)});
            }
           tabel_record.setModel(tabelpegawai);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
                    
          
        }
        
    }
    
}
