/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.conek;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;







/**
 *
 * @author imam
 */
public class transaksioffline extends javax.swing.JFrame {

    JasperReport jasRep;
    JasperDesign jasDes;
    JasperPrint jasPri;
    Map<String, Object> penjualan = new HashMap<String, Object>();
    
     Connection _Cnn;
    conek getCnn = new conek();
     SimpleDateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
      
    SimpleDateFormat dateformat2 = new SimpleDateFormat("YYYY-MM-dd");
    int count = 0,stok_awal;
    String idpenjualan, idbarang, idhapus, ubah;
    boolean belumtransaksi = false;
    double total;
    
      Statement statement ;
       ResultSet resultSet;
    
     
    private String STR = "  ";
private int a, b, c, d, e;

private DefaultTableModel model;


public String idmember,nama,tingkatan,diskon,jmlptong;

 public String getIdMember() {
        return idmember;
    }
 public String getNama(){
           return nama;
    }
 public String getTingkatan(){
        return tingkatan;
    }
 public String getDisk() {
        return diskon;
    }
 public String getJptong() {
        return jmlptong;
    } 
    /**
     * Creates new form transaksioffline
     */






    public transaksioffline() {
      //  setTitle("Penjualan Barang");
        initComponents();
        kondisiAwal();
       // select();
       // selectTrans();
        loadcombodata();
        loadcomtoko();
        /*
       DefaultTableModel model = new DefaultTableModel();
         tabel_barang.setModel(model);
        model.addColumn("No. Transaksi");
        model.addColumn("Tgl. Transaksi");  
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total Harga");
        */
        loadData();
        
        
        
        
    }

   
    
    public Connection con;
    private String sql;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement ps;
    private DefaultTableModel dtm;
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btninsert = new javax.swing.JButton();
        btntransaksi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jdiskon = new javax.swing.JTextField();
        jmember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jjmlhpotong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jcmember = new javax.swing.JTextField();
        jnama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbarang = new javax.swing.JTextField();
        jtgl = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jhargaawal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jjmlhbeli = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jstok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jctoko = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jtotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jhargatotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jkembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jhitung = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jdiskoooon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        label60 = new javax.swing.JLabel();
        lb_penj = new javax.swing.JLabel();
        jpenjualan = new javax.swing.JTextField();
        btncarijual = new javax.swing.JButton();
        jjumlah = new javax.swing.JLabel();
        jtot = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_jual = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(49, 163, 246));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "FORM JUAL BARANG ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jPanel2.setBackground(new java.awt.Color(132, 196, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "navigasi"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btninsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OK.png"))); // NOI18N
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });

        btntransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add_1.png"))); // NOI18N
        btntransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntransaksi)
                    .addComponent(btninsert)
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btntransaksi)
                .addGap(13, 13, 13)
                .addComponent(btninsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(132, 196, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Input Data Member"));

        jLabel8.setText("Tingkatan");

        jLabel3.setText("ID Member");

        jLabel13.setText("Diskon");

        jLabel14.setText("jml potongan");

        jButton2.setText("Ambil Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdiskon)
                            .addComponent(jcmember, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jnama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jmember, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jjmlhpotong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjmlhpotong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(52, 69, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(132, 196, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Input Barang Yang di Beli"));

        jLabel2.setText("ID Barang");

        jbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbarangKeyReleased(evt);
            }
        });

        jLabel5.setText("Tgl");

        jLabel4.setText("Harga ");

        jjmlhbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jjmlhbeliKeyReleased(evt);
            }
        });

        jLabel12.setText("Jumlah Beli");

        jLabel11.setText("Total Harga");

        jLabel6.setText("Jumlah Barang");

        jctoko.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Nama Toko");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jhargaawal))
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jstok, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jctoko, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jjmlhbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjmlhbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jctoko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jhargaawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(132, 196, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "perhitungan"));

        jLabel7.setText("Total Harga");

        jbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbayarKeyReleased(evt);
            }
        });

        jLabel9.setText("Uang Bayar");

        jkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkembaliActionPerformed(evt);
            }
        });

        jLabel10.setText("Uang Kembali");

        jhitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buy_1.png"))); // NOI18N
        jhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhitungActionPerformed(evt);
            }
        });

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jLabel18.setText("Rp");

        jLabel17.setText("Rp");

        jLabel16.setText("Rp");

        jLabel19.setText("Diskon");

        jLabel20.setText("Rp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jhargatotal)
                            .addComponent(jkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jdiskoooon, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnprint)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jhargatotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdiskoooon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(18, 71, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprint, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jhitung, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(132, 196, 242));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Tabel Stok Barang"));

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_barang);

        jScrollPane1.setViewportView(jScrollPane2);

        label60.setText("ID_PENJUALAN");

        lb_penj.setText("-");

        btncarijual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Display.png"))); // NOI18N
        btncarijual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarijualActionPerformed(evt);
            }
        });

        jjumlah.setText("0");

        jtot.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label60)
                .addGap(18, 18, 18)
                .addComponent(jpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(lb_penj, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btncarijual)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jjumlah)
                    .addComponent(jtot))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label60)
                            .addComponent(lb_penj)
                            .addComponent(jpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncarijual)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jjumlah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtot)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(132, 196, 242));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Tabel Jual Barang"));

        tabel_jual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_jual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_jualMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_jual);

        jScrollPane3.setViewportView(jScrollPane4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void jkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkembaliActionPerformed

    private void btntransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaksiActionPerformed
         
            
         try {
             AutoID();
             kondisiAktif();
             jbarang.requestFocus(true);
         } catch (SQLException ex) {
             Logger.getLogger(transaksioffline.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_btntransaksiActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        TambahData();
        loadData();
        tampilkan();
    }//GEN-LAST:event_btninsertActionPerformed

    private void jjmlhbeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jjmlhbeliKeyReleased
        // TODO add your handling code here:
        
        a = Integer.parseInt(jhargaawal.getText());
        b = Integer.parseInt(jjmlhbeli.getText());
        c=a*b;
        jtotal.setText(String.valueOf(c));
        
        /*
        int q1=Integer.parseInt(this.jjmlhbeli.getText());
        int q2=Integer.parseInt(this.jjumlah.getText());
        if (q1 <= q2)
        {
        String qtys=jjmlhbeli.getText();       
       String totals=jhrg.getText();
        double qtysd=Double.parseDouble(qtys);
        double totalsd=Double.parseDouble(totals);
        DecimalFormat df = new DecimalFormat("#.##");
        jhargatotal.setText(df.format(qtysd * totalsd));
        }else{
            jjmlhbeli.setText(null);
        }
        */
    }//GEN-LAST:event_jjmlhbeliKeyReleased

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        // TODO add your handling code here:
        
        
         int baris = tabel_barang.getSelectedRow();
        if (baris != -1) {
            jbarang.setText(tabel_barang.getValueAt(baris, 0).toString());
            jhargaawal.setText(tabel_barang.getValueAt(baris,6).toString());
            jstok.setText(tabel_barang.getValueAt(baris,7).toString());
        
        }
        
        /*
        DefaultTableModel model = new DefaultTableModel();
        tabel_barang.setModel(model);

        int i=tabel_barang.getSelectedRow();

        if(i==-1)
        {
            return;
        }
        String kode=(String) model.getValueAt(i, 0);

        String kodebar=(String) model.getValueAt(i, 2);
        String nama_barang=(String) model.getValueAt(i, 3);
        String jml=(String) model.getValueAt(i, 4);

        String sql1="Update barang Set jumlah=jumlah + ? where id_barang=?";
        String sql="Delete from penjualan where no_transaksi=? AND id_barang=?";
        try {
            conek getCnn = new conek();
            con= null;
            con= (com.mysql.jdbc.Connection) getCnn.getConnection();

            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, jml);
            st.setString(2, kodebar);
            st.setString(3, nama_barang);

            st.executeUpdate();
            st.close();

            com.mysql.jdbc.PreparedStatement st2=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            st2.setString(1, kode);
            st2.setString(2, kodebar);
            st2.executeUpdate();
            st2.close();

        }catch(SQLException e) {
            System.out.println(e);
        }finally{
            loadData();
        }  */

    }//GEN-LAST:event_tabel_barangMouseClicked

    
    
    
    
    
    private void btncarijualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarijualActionPerformed
        // TODO add your handling code here:
        tampilkan();
    }//GEN-LAST:event_btncarijualActionPerformed

    private void jhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhitungActionPerformed
        // TODO add your handling code here:
        
       // DefaultTableModel tabelpegawai = new DefaultTableModel();
   
       int jumlah = tabel_jual.getRowCount();
//int totalBiaya = 0;
int totalsemua =0 ;
//int jumlahpotongan = 0;
int jumlahpotongan=0;
//int jumlahBarang1=0;
int jumlahBarang=0;
int totalBiaya=0;
int totalBiaya1=0;
int hasil=0;
int jumlahpotongantotal ,jumlahBarang1, hargaBarang ;


c = Integer.parseInt(jjmlhpotong.getText());
d = Integer.parseInt(jdiskon.getText());
 
TableModel tabelModel;
tabelModel = tabel_jual.getModel();
       for (int i=0; i<jumlah; i++){
 //   jumlahBarang1 = jumlahBarang1 + (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    jumlahBarang1= Integer.parseInt(tabelModel.getValueAt(i, 5).toString());
    jumlahBarang= jumlahBarang + (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    hargaBarang = (Integer.parseInt(tabelModel.getValueAt(i, 6).toString()));
        if(jumlahBarang < c){
          //  totalBiaya=totalBiaya+(jumlahBarang*hargaBarang);
        totalBiaya=totalBiaya+hargaBarang;
        }else {
           // hargaBarang=hargaBarang;
            jumlahpotongan= (d*jumlahBarang)  ;
            
            hasil=hasil+(hargaBarang);
           
        // totalBiaya=totalBiaya+(hasil-jumlahpotongan);
        }//JOptionPane.showMessageDialog(null, hargaBarang);
   
       }
        totalBiaya=totalBiaya+(hasil-jumlahpotongan);
        
    jhargatotal.setText(String.valueOf(totalBiaya));
    jdiskoooon.setText(String.valueOf(jumlahpotongan));
    jjumlah.setText(String.valueOf(jumlahBarang));
   // jtot.setText(String.valueOf(hargaBarang));
    
    /*    
       int jumlah = tabel_jual.getRowCount();
//int totalBiaya = 0;
int totalsemua =0 ;
//int jumlahpotongan = 0;
int jumlahpotongan=0;
int jumlahBarang=0;
int totalBiaya=0;
int jumlahpotongantotal;
int  hargaBarang   ;
int jumlahBarang1=0;
c = Integer.parseInt(jjmlhpotong.getText());
d = Integer.parseInt(jdiskon.getText());
 e=0 ;
TableModel tabelModel;
tabelModel = tabel_jual.getModel();

for (int i=0; i<jumlah; i++){
    jumlahBarang1 = jumlahBarang1 + (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    
    jumlahBarang = (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    hargaBarang = Integer.parseInt(tabelModel.getValueAt(i, 4).toString());
    //jumlahbaju = Integer.parseInt(tabelModel.getValueAt(i, 5).toString());
    //jumlahpotongan = jumlahpotongan + (jumlahBarang / c) * d;
    e = jumlahBarang1-c;
    if((jumlahBarang-e) >=c){
   jumlahpotongantotal =   ((jumlahBarang1)*d);
    
      
    
        
         totalBiaya =  (jumlahBarang1*hargaBarang);
    
   totalsemua = totalsemua + (totalBiaya - jumlahpotongantotal);
  //  jumlahpotongan = jumlahpotongantotal;
  // jumlahpotongantotal =   (jumlahBarang*(Integer.parseInt(jdiskon.getText())));
   
   jumlahpotongan = jumlahpotongan +  (jumlahpotongantotal);
   
       
    } else if (jumlahBarang < c)
            { 
    // jumlahpotongantotal =   ((jumlahBarang)*d);
                
             totalBiaya =  (jumlahBarang*hargaBarang);  
    
    totalsemua =   (totalsemua + (totalBiaya ));
    
    jumlahpotongan=0;  
    
    }
   
}
       
jTextField1.setText(String.valueOf(jumlahBarang1));
jdiskoooon.setText(String.valueOf(jumlahpotongan));
jhargatotal.setText(String.valueOf(totalsemua));
        */
    }//GEN-LAST:event_jhitungActionPerformed

    private void hitungtanpadiskon(){
   
    
    }
    
     private void hitung1() {
              
          
        
         
               
    /*     for (int i=0; i<jumlah; i++){
 //   jumlahBarang1 = jumlahBarang1 + (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    
    jumlahBarang = (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    hargaBarang = Integer.parseInt(tabelModel.getValueAt(i, 4).toString());
        //To change body of generated methods, choose Tools | Templates.
        totalBiaya =  (jumlahBarang*hargaBarang);  
    
    totalsemua =   (totalsemua + (totalBiaya ));
         }*/
    }
    private void hitung2() {
       //To change body of generated methods, choose Tools | Templates.
   
    }
    
    
    private void jbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbayarKeyReleased
        // TODO add your handling code here:
        a = Integer.parseInt(jbayar.getText());
        b = Integer.parseInt(jhargatotal.getText());
        int hasil = a - b;
        jkembali.setText(STR + hasil);
        
    }//GEN-LAST:event_jbayarKeyReleased

    private void tabel_jualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_jualMouseClicked
        // TODO add your handling code here:
        
        int i=tabel_jual.getSelectedRow();
        
        if(i==-1)
        {
            return;
        }
        String kode=(String) tabel_jual.getValueAt(i, 0);        
               
        String kodebar=(String) tabel_jual.getValueAt(i, 3);
        String jml=(String) tabel_jual.getValueAt(i, 5);
        
        String sql1="Update barang Set jumlah=jumlah + ? where id_barang=?";
        String sql="Delete from penjualan where no_transaksi=? AND id_barang=?";
    try {        
    
         conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
            
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, jml);
            st.setString(2, kodebar);
            st.executeUpdate();
            st.close();
            
            com.mysql.jdbc.PreparedStatement st2=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            st2.setString(1, kode);
            st2.setString(2, kodebar);
            st2.executeUpdate();
            st2.close();
            
    }catch(SQLException e) {
        System.out.println(e);
        JOptionPane.showMessageDialog(null, e.getMessage());
    }finally{
        
        loadData();
        tampilkan();
    }
        
    }//GEN-LAST:event_tabel_jualMouseClicked

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
      SimpleDateFormat date;
        date= new SimpleDateFormat("yyyy-MM-dd ");
       lb_penj.setText(date.format(jtgl.getDate()));
        
       updatetransaksi();
        simpan();
        print();
        
        
        
    }//GEN-LAST:event_btnprintActionPerformed

    private void jbarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbarangKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tabelpegawai = new DefaultTableModel();
        tabelpegawai.addColumn("ID BARANG");
        tabelpegawai.addColumn("NAMA BARANG");
        tabelpegawai.addColumn("JENIS PAKAIAN");
        tabelpegawai.addColumn("UKURAN");
        tabelpegawai.addColumn("BRAND");
        
        tabelpegawai.addColumn("WARNA");
        tabelpegawai.addColumn("HARGA (RP)");
        tabelpegawai.addColumn("STOK");
        try {
            
           conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
         String sql = "select * from barang where id_barang like '%" + jbarang.getText() + "%'" ;
        Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
            
           
            
            
            while (res.next()) {
                tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)
                ,res.getString(6),res.getString(7),res.getString(8)});
            }
           tabel_barang.setModel(tabelpegawai);
        } catch (Exception e) {
          
        }
    }//GEN-LAST:event_jbarangKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ambilmember fDB = new ambilmember();
        fDB.fAB = this;
        fDB.setVisible(true);
        fDB.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksioffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksioffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksioffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksioffline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksioffline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncarijual;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btntransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jbarang;
    private javax.swing.JTextField jbayar;
    private javax.swing.JTextField jcmember;
    private javax.swing.JComboBox<String> jctoko;
    private javax.swing.JTextField jdiskon;
    private javax.swing.JTextField jdiskoooon;
    private javax.swing.JTextField jhargaawal;
    private javax.swing.JTextField jhargatotal;
    private javax.swing.JButton jhitung;
    private javax.swing.JTextField jjmlhbeli;
    private javax.swing.JTextField jjmlhpotong;
    private javax.swing.JLabel jjumlah;
    private javax.swing.JTextField jkembali;
    private javax.swing.JTextField jmember;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jpenjualan;
    private javax.swing.JTextField jstok;
    private com.toedter.calendar.JDateChooser jtgl;
    private javax.swing.JLabel jtot;
    private javax.swing.JTextField jtotal;
    private javax.swing.JLabel label60;
    private javax.swing.JLabel lb_penj;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_jual;
    // End of variables declaration//GEN-END:variables

    private void kondisiAwal() {
        //To change body of generated methods, choose Tools | Templates.
    
        jbarang.setEnabled(false);
        jtgl.setEnabled(false);
        jhargaawal.setEnabled(false);
        jstok.setEnabled(false);
        jtotal.setEnabled(true);
         jdiskon.setEnabled(false);
         jjmlhpotong.setEnabled(false);
         jhargatotal.setEnabled(false);
          jkembali.setEnabled(false);
        //tabel_transaksi.setEnabled(false);
      
        jButton2.setEnabled(false);
       
        tabel_barang.setEnabled(false);
        tabel_jual.setEnabled(true);
        jmember.setEnabled(false);
       jpenjualan.setEnabled(false);
       jcmember.setEnabled(false);
      
       jjmlhbeli.setEnabled(false);
        
        jbayar.setEnabled(false);
        btninsert.setEnabled(false);
        //btndelete.setEnabled(false);
        jButton1.setEnabled(false);
        btncarijual.setEnabled(false);
        jhitung.setEnabled(false);
        btnprint.setEnabled(false);
        
        jmember.setEnabled(false);
        jnama.setEnabled(false);
        jcmember.setEnabled(false);
       
        
        
        
    }
    
    private void kondisiAktif(){
        jbarang.setEnabled(true);
       tabel_barang.setEnabled(true);
        tabel_jual.setEnabled(true);
       // jmember.setEnabled(true);
       jpenjualan.setEnabled(true);
      // jcmember.setEnabled(true);
      
       jjmlhbeli.setEnabled(true);
        jButton2.setEnabled(true);
        jbayar.setEnabled(true);
        btninsert.setEnabled(true);
      //  btndelete.setEnabled(true);
        jButton1.setEnabled(true);
        btncarijual.setEnabled(true);
        jhitung.setEnabled(true);
       btnprint.setEnabled(true);
        
        lb_penj.setEnabled(true);
        lb_penj.setText("0");
    }

    private void select() {
         //To change body of generated methods, choose Tools | Templates.
        
         
         
         
         
         /*
          DefaultTableModel tabelpegawai = new DefaultTableModel();
        tabelpegawai.addColumn("ID BARANG");
        tabelpegawai.addColumn("NAMA BARANG");
        tabelpegawai.addColumn("HARGA (RP)");
        tabelpegawai.addColumn("JUMLAH");
        
        try {
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        String sql = "select id_barang, nama_barang, harga, jumlah from barang where jumlah > 0 ";
        Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
        while (res.next()){
            tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)
            });
        }
        tabel_barang.setModel(tabelpegawai);
        } catch(Exception e){}*/
         
         
   /*
   Object header[] = {"ID_BARANG", "NAMA_BARANG", "HARGA_JUAL", "JUMLAH_STOK"};
   DefaultTableModel defaultTableModel = new DefaultTableModel(null,header);
   tabel_barang.setModel(defaultTableModel);
   int baris = tabel_barang.getRowCount();
   for (int i = 0; i < baris; i++) {
       defaultTableModel.removeRow(i);
     
   }
  
   try {
       conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
         String sql="select id_barang,nama_barang,harga,jumlah from barang where jumlah > 0";
        Statement stat = con.createStatement();
        ResultSet res = stat.executeQuery(sql);
       
        
        while (rs.next()) {
            String kolom1 = rs.getString(1);
            String kolom2 = rs.getString(2);
            String kolom3 = rs.getString(3);
            String kolom4 = rs.getString(4);
            String kolom [] = {kolom1, kolom2, kolom3, kolom4};
            defaultTableModel.addRow(kolom);

        }   
       
        
   }catch (Exception e) {
       JOptionPane.showMessageDialog(null, e.getMessage());
   }
*/
   
    }
    
   private String AutoID() throws SQLException{
      
       String sql = "select max(no_transaksi) from penjualan";
            String idPenjualan = "";
       try{
           
            conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
           
            Date date= new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = dateFormat.format(date);
            jtgl.setDate(date);
            SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd.MM.YYYY");
            String tanggal2 = dateFormat2.format(date);
            count ++;
         //  String sqlTanggal = "SELECT no_transaksi FROM penjualan limit 1";
           // resultSet = statement.executeQuery(sqlTanggal);
         //  while (resultSet.next()) {
           //    String data1 = resultSet.getString(1);
             
               //   count = Integer.valueOf(data1);
                //  count++;
                  
          //  }
            
            idPenjualan = "TJ." + tanggal + "." + count ;
           // String sql = "INSERT INTO penjualan VALUES('"+ idPenjualan + "',' coba ',NOW(),0 )";
            //statement.executeQuery(sql);
            jpenjualan.setText(""+(idPenjualan));
                
       } catch (SQLException e){
       
           JOptionPane.showMessageDialog(null, "terjadi kesalahan"+ e.getMessage());
       
       }
       return idPenjualan;
       
   }

   
   private void AutoNumber(){
   
       String sql = "select max(no_transaksi) from penjualan";
        try{
            
             conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
            
            statement = con.createStatement();
            rs = statement.executeQuery(sql);
            while (rs.next()){
                int a = rs.getInt(1);
                jpenjualan.setText(""+ Integer.toString(a+1));
            }
        }catch (Exception e){
            System.out.println(""+ e.getMessage());
        }
    
   
   }
   
    private void selectTrans() {
    /* DefaultTableModel tabelpegawai = new DefaultTableModel();
        tabelpegawai.addColumn("ID BARANG");
        tabelpegawai.addColumn("NAMA BARANG");
        tabelpegawai.addColumn("HARGA (RP)");
        tabelpegawai.addColumn("JUMLAH");
        tabelpegawai.addColumn("TOTAL HARGA");
   
        */
        
//To change body of generated methods, choose Tools | Templates.
    

    }

    private void TambahData() {
        //To change body of generated methods, choose Tools | Templates.
        /*
        try {
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        String sql="insert into penjualan values('"+jpenjualan.getText()
                +"','"+jtgl.getDate()
                +"','"+jbarang.getText()
                +"','"+jhargaawal.getText()
                +"','"+jjmlhbeli.getText()
                +"','"+jhrgtotal.getText()+"')";
        st=con.createStatement();
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Data sukses tersimpan");
        
        //kosong();
       tampilkan();
        } catch (Exception  e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
        */
       
        
      String no=this.jpenjualan.getText();
      String kode=(String) this.jbarang.getText();
    java.util.Date tgl=(java.util.Date) this.jtgl.getDate();
    String member = this.jmember.getText();
   
    String Harga=this.jhargaawal.getText();
    String Jml=this.jjmlhbeli.getText();
    String total=this.jtotal.getText();
    String tujuan=this.lb_penj.getText();
    String ongkir=this.lb_penj.getText();
    String toko=this.lb_penj.getText();
    String beli=this.lb_penj.getText();
    String nama_toko=(String) this.jctoko.getSelectedItem();
    

 try {
            String sql1="Select * from penjualan where no_transaksi='" + no + "' AND id_barang='" + kode +  "'";
           
             conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
            
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            ResultSet rs=st.executeQuery(sql1);
             if (rs.next())
            {
            String sql = "UPDATE penjualan Set jumlah=jumlah + ?,total_harga= total_harga + ? where no_transaksi='" + no + "' AND id_barang='" + kode + "'";
            com.mysql.jdbc.PreparedStatement p2=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            
            p2.setString(1, Jml);
            p2.setString(2, total);           
            p2.executeUpdate();
            p2.close();
            this.updatebarang(Jml, kode);
            
            }else{
            String sql = "Insert into penjualan values (?,?,?,?,?,?,?,?,?,?,?)";
           
            com.mysql.jdbc.PreparedStatement p=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            p.setString(1, no);
            p.setDate(2,  new java.sql.Date(tgl.getTime()));         
            p.setString(3, member);
            p.setString(4, kode);                        
            p.setString(5, Harga);                        
            p.setString(6, Jml);                        
            p.setString(7, total); 
             p.setString(8, tujuan);
              
               p.setString(9, toko);
                p.setString(10, beli);
                p.setString(11, nama_toko);
              
             
            p.executeUpdate();
            p.close();
           
            this.updatebarang(Jml, kode);
            this.updatemember(tgl, member);
            //this.updatetingkatan(tgl,member);
            
            } 
                    
                    
        }catch(Exception e){
            System.out.println(e);
 JOptionPane.showMessageDialog(null, e.getMessage());           
        }
 
 finally{
            loadData();
            
        }    
 
    
    }

    
    private void tampilkan(){
    
    DefaultTableModel tabelpegawai = new DefaultTableModel();
        tabelpegawai.addColumn("NO TRANSAKSI");
        tabelpegawai.addColumn("TANGGAL");
        tabelpegawai.addColumn("ID MEMBER");
        tabelpegawai.addColumn("ID BARANG");
        tabelpegawai.addColumn("HARGA");
        tabelpegawai.addColumn("JUMLAH");
        tabelpegawai.addColumn("TOTAL HARGA");
       
        
        try {
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        //String sql = "select * from penjualan where no_transaksi like '%" + jpenjualan.getText() +"%'";
        String sql = "select * from penjualan where no_transaksi='"+jpenjualan.getText()+"'AND idmember='"+jmember.getText() + "'";
        Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
        while (res.next()){
            tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)
            ,res.getString(5),res.getString(6),res.getString(7)});
        }
        tabel_jual.setModel(tabelpegawai);
        } catch(Exception e){
        
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
    }
    
    
    
    private void loadData() {
         //To change body of generated methods, choose Tools | Templates.
         DefaultTableModel model = new DefaultTableModel();
         model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {  
            conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                
           // Connection c=ClassDB.getkoneksi();
            Statement s= con.createStatement();
            String sql="Select * from penjualan where no_transaksi='" + this.jpenjualan.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o=new Object[6];
                o[0]=r.getString("no_transaksi");
                o[1]=r.getString("tgl_transaksi");               
                o[2]=r.getString("kd_barang");
                o[3]=r.getString("harga");
                o[4]=r.getString("jumlah");                
                o[5]=r.getString("totalharga");
                
                model.addRow(o);
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }

    private void updatebarang(String jumlah, String KodeBar) {
        //To change body of generated methods, choose Tools | Templates.
        
         String sql1="Update barang Set jumlah=jumlah - ? where id_barang=?";
    try {        
  
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, jumlah);
            st.setString(2, KodeBar);
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
    }
    
    public void loadcombodata() {
     
    }

    private void updatemember(Date tgl,String member) {
         
         String sql1="Update member Set tgl=? where idmember=?";
    try {        
  
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
      String sql2 = "SELECT * from member";
            Statement st2  =con.createStatement();
            ResultSet sr2 = st2.executeQuery(sql2);
            while(sr2.next()){
        String tanggal = sr2.getString(9);
        String[] tgl_trans =  tanggal.split("-");
        String sql3 = "Select idmember,sum(jumlah) as jml from penjualan where idmember='"+sr2.getString(1)+"' and date(tgl) between date('"+tanggal+"') and date('"+tgl_trans[0]+"-"+((Integer.valueOf(tgl_trans[1]))+1)+"-"+tgl_trans[2]+"')";
        Statement st3 = con.createStatement();
        ResultSet sr3 = st3.executeQuery(sql3);
        String[] tgl2 = (tgl.toString()).split("-");
        if((Integer.valueOf(tgl2[0])) > ((Integer.valueOf(tgl_trans[0]))) || ((Integer.valueOf(tgl2[1]))) > ((Integer.valueOf(tgl_trans[1]))+1) && ((Integer.valueOf(tgl2[2]))) >((Integer.valueOf(tgl_trans[2]))) ){
        while(sr2.next()){
            if((sr3.getString(7).equals("DISTRIBUTOR"))){
                if(sr3.getInt(2) < 30){
                    this.updatetingkatan("SUPPLIER", sr3.getString(1));
                }
            }
            if((sr3.getString(7).equals("SUPPLIER"))){
                if(sr3.getInt(2) < 25){
                    this.updatetingkatan("AGEN", sr3.getString(1));
                }
            }if((sr3.getString(7).equals("AGEN"))){
                if(sr3.getInt(2) < 7){
                    this.updatetingkatan("GROSIR", sr3.getString(1));
                }
            }
        }
        }
        }
       
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setDate(1, new java.sql.Date(tgl.getTime())); 
            st.setString(2, member);
            
           
         
            st.executeUpdate();
            st.close();
           
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }

    private void hapus() {
      /*  
        String no=this.jpenjualan.getText();
      String kode=(String) this.jbarang.getText();
    java.util.Date tgl=(java.util.Date) this.jtgl.getDate();
    String member = this.jmember.getText();
   
    String Harga=this.jhargaawal.getText();
    String Jml=this.jjmlhbeli.getText();
    String total=this.jhrgtotal.getText();
    String tujuan=this.lb_penj.getText();
    String ongkir=this.lb_penj.getText();
    String toko=this.lb_penj.getText();
    String beli=this.lb_penj.getText();
      
      try {
            String sql1="Select * from penjualan where no_transaksi='" + no + "' AND id_barang='" + kode +  "'";
           
             conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
            
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            ResultSet rs=st.executeQuery(sql1);
             if (rs.next())
            {
            String sql = "UPDATE penjualan Set jumlah=jumlah - ?,total_harga= total_harga - ? where no_transaksi='" + no + "' AND id_barang='" + kode + "'";
            com.mysql.jdbc.PreparedStatement p2=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            
            p2.setString(1, Jml);
            p2.setString(2, total);           
            p2.executeUpdate();
            p2.close();
            this.updatebarangdelete(Jml, kode);
            
            }else{
                 String sql = "Delete from penjualan where id_barang='" + kode + "'AND no_transaksi= '"+ no + "'";
          //  String sql = "Delete into penjualan values (?,?,?,?,?,?,?,?,?,?,?)";
           
            com.mysql.jdbc.PreparedStatement p=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            p.setString(1, no);
            p.setDate(2,  new java.sql.Date(tgl.getTime()));         
            p.setString(3, member);
            p.setString(4, kode);                        
            p.setString(5, Harga);                        
            p.setString(6, Jml);                        
            p.setString(7, total); 
             p.setString(8, tujuan);
              p.setString(9, ongkir);
               p.setString(10, toko);
                p.setString(11, beli);
              
             
            p.executeUpdate();
            p.close();
           
            this.updatebarangdelete(Jml, kode);
            this.updatemember(tgl, member);
            //this.updatetingkatan(tgl,member);
            
            } 
                    
                    
        }catch(Exception e){
            System.out.println(e);
 JOptionPane.showMessageDialog(null, e.getMessage());           
        }
 
 finally{
            loadData();
            
        }    
       */
      
       
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???", "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
       if (ok==0)
       {
        try
         {
             
            String sql="delete from penjualan where id_barang='"+jbarang.getText()+"'AND idmember='"+jmember.getText()+"'";
            //String sql1="Update barang Set jumlah=jumlah + ? where id_barang='"+jbarang.getText()+"'";
            PreparedStatement st=con.prepareStatement(sql);
           // PreparedStatement stt=con.prepareStatement(sql1);
           // stt.executeUpdate();
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Data Sukses");
            
          
            
        //    kosong();
        tampilkan();
        
        
        
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       }
          
        
    }

    private void hapustabel() {
        
        //private DefaultTableModel model;
        
        
        
        
    }

    private void updatestok(String Jml, String kode) {
        
          String sql1="Update barang Set stok=stok + ? where id_barang=?";
    try {        
  
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, Jml);
            st.setString(2, kode);
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
    }

    private void updatetingkatan(String grosir, String member) {
        
        String sql1="Update member Set tingkatan=  ? where idmember=?";
        
    try {        
  
        conek getCnn = new conek();
        
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, tingkatan); 
            st.setString(2, member);
            
           
         
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
    }

    private void updatebarangdelete(String Jml, String kode) {
         //To change body of generated methods, choose Tools | Templates.
          String sql1="Update barang Set jumlah=jumlah + ? where id_barang=?";
    try {        
  
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, Jml);
            st.setString(2, kode);
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }

    void itemTerpilih() {
         //To change body of generated methods, choose Tools | Templates.
         ambilmember fDB = new ambilmember();
        fDB.fAB = this;
        jmember.setText(idmember);
        jnama.setText(nama);
        jcmember.setText(tingkatan);
        jdiskon.setText(diskon);
        jjmlhpotong.setText(jmlptong);
        //txtNama.setText(nama);
        
    }

    private void loadcomtoko() {
         //To change body of generated methods, choose Tools | Templates.
         try {        
        jctoko.removeAllItems();
        
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                    
        
            Statement s= con.createStatement();
            String sql="Select * from toko";
            
           
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                jctoko.addItem(r.getString("nama"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        } 
    }

    private void updatetransaksi(){
    
        
        
      
                try {
                     String sql="update member set tgl=? where idmember='"+jmember.getText()+"'";
                
                     PreparedStatement st=con.prepareStatement(sql);
                //if(ok==0)
                {
                try
                    {
                        st.setString(1,lb_penj.getText());
                        
                        
                        
                        st.executeUpdate();
      
       
        //String sql="insert into pembayaran values('"+jpenjualan.getText()
                
       
        JOptionPane.showMessageDialog(null, "Data sukses tersimpan");
        
      
        
        } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Data GAGAl");
            }
        
                }   
    }catch (Exception a){}
    
    }
                
    private void simpan() {
         //To change body of generated methods, choose Tools | Templates.
         
          try {
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        String sql="insert into pembayaran values('"+jpenjualan.getText()
                +"','"+jmember.getText()               
                +"','"+jhargatotal.getText()
                +"','"+jbayar.getText()
                +"','"+jkembali.getText()
                +"','"+jdiskoooon.getText()
                +"','"+lb_penj.getText()
                
                +"')";
        st=con.createStatement();
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Data sukses tersimpan");
        
      
        
        } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Data GAGAl");
            }
         
    }

    private void print() {
       //To change body of generated methods, choose Tools | Templates.
        try {
           
           // Class.forName("com.mysql.jdbc.Driver");
           // con = DriverManager.getConnection("jdbc:mysql://localhost/toko");
         
            
       
           
             
            File file = new File("src/laporan/report5.jrxml");
            jasDes = JRXmlLoader.load(file);
            //penjualan.clear();
            
            String ttrans = (jpenjualan.getText());
            penjualan.put("no_transaksi", ttrans);
            
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, penjualan, con);
            JasperViewer.viewReport(jasPri, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        }
        
    }

   

    

    

   
    
    
}

