/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;


import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.conek;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author imam
 */
public class transaksionline extends javax.swing.JFrame {

    JasperReport jasRep;
    JasperDesign jasDes;
    JasperPrint jasPri;
    Map<String, Object> penjualan = new HashMap<String, Object>();
    
    
    Connection _Cnn;
    conek getCnn = new conek();
     SimpleDateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
      
    SimpleDateFormat dateformat2 = new SimpleDateFormat("YYYY-MM-dd");
    int count = 0,stok_awal;
    String idpenjualan, idbarang, idhapus, ubah;
    boolean belumtransaksi = false;
    double total;
    
      Statement statement ;
       ResultSet resultSet;
       
        private String STR = "  ";
private int a, b, c, d, e;

public String idmember,nama,tingkatan,diskon,jmlptong;


 public String getIdMember() {
        return idmember;
    }
 public String getNama(){
        return nama;
 }
 public String getTingkatan(){
        return tingkatan;
 }
 public String getDisk() {
        return diskon;
    }
 public String getJptong() {
        return jmlptong;
    }
 
 public String namatoko,alamat,hp,bbmtoko,web;
 
  public String getNmtoko() {
        return namatoko;
    }
 public String getAlamat(){
        return alamat;
 }
 public String getHp(){
        return hp;
 }
 public String getBBM() {
        return bbmtoko;
    }
 public String getWeb() {
        return web;
    }
    /**
     * Creates new form transaksionline
     */
    public transaksionline() {
        initComponents();
         
         loadData();
         kondisiawal();
         loadcomatm();
         loadcomtoko();
         auto_number();
         
    }

     public Connection con;
    private String sql;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement ps;
    private DefaultTableModel dtm;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtgl = new com.toedter.calendar.JDateChooser();
        jhargaawal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jjmlhbeli = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jstok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jhrgbrng = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jidmember = new javax.swing.JTextField();
        jnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jkirim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbiayakrm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jrekbeli = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jpotongan = new javax.swing.JTextField();
        jjmlhpakaian = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnmember = new javax.swing.JButton();
        jtingkatan = new javax.swing.JTextField();
        jcnama = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jtransaksi = new javax.swing.JButton();
        jinsert = new javax.swing.JButton();
        jprint = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtotharga = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtotbayar = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnprint = new javax.swing.JButton();
        jdiskon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_stok = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jatm = new javax.swing.JTextField();
        jcatm = new javax.swing.JComboBox<>();
        lb_faktur = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_jual = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel8.setBackground(new java.awt.Color(49, 163, 246));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "FORM PENJUALAN"));

        jPanel2.setBackground(new java.awt.Color(132, 196, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "barang"));

        jbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbarangKeyReleased(evt);
            }
        });

        jLabel12.setText("ID Barang");

        jLabel13.setText("Tanggal");

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah Beli");

        jjmlhbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jjmlhbeliKeyReleased(evt);
            }
        });

        jLabel14.setText("Stok");

        jLabel6.setText("Total Harga Barang");

        jLabel19.setText("Rp.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(jhargaawal))
                    .addComponent(jtgl, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jstok, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jjmlhbeli)
                    .addComponent(jhrgbrng))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jjmlhbeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jhrgbrng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jtgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jhargaawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel19))))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(132, 196, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "coba"));

        jLabel2.setText("ID Member");

        jLabel3.setText("Nama ");

        jLabel7.setText("Tujuan Kirim");

        jLabel8.setText("Biaya Kirim");

        jLabel11.setText("No. Rekening");

        jLabel10.setText("Tingkatan");

        jLabel17.setText("Diskon");

        jLabel18.setText("Jumlah Pakaian");

        btnmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/People.png"))); // NOI18N
        btnmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmemberActionPerformed(evt);
            }
        });

        jcnama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Nama Toko");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jkirim, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpotongan, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jjmlhpakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbiayakrm, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtingkatan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jidmember, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnmember))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcnama, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                                .addComponent(jrekbeli, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtingkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jidmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnmember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jkirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjmlhpakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jbiayakrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrekbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "tombol"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add_1.png"))); // NOI18N
        jtransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtransaksiActionPerformed(evt);
            }
        });

        jinsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OK.png"))); // NOI18N
        jinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinsertActionPerformed(evt);
            }
        });

        jprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jinsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jprint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jtransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jinsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jprint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "bayar"));

        jLabel15.setText("Total Harga");

        jLabel16.setText("Bayar");

        btnhitung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buy_1.png"))); // NOI18N
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel20.setText("Rp.");

        jLabel21.setText("Rp.");

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jLabel9.setText("Diskon");

        jLabel22.setText("Rp.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnhitung)
                        .addGap(18, 18, 18)
                        .addComponent(btnprint)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jLabel20))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdiskon)
                            .addComponent(jtotharga)
                            .addComponent(jtotbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtotharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtotbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhitung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(132, 196, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "tabel stok barang"));

        tabel_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_stok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_stokMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_stok);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(132, 196, 242));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "No Faktur"));

        jcatm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih" }));
        jcatm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcatmActionPerformed(evt);
            }
        });

        btncari.setText("cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel23.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lb_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncari)
                .addGap(59, 59, 59)
                .addComponent(jcatm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jatm, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(37, 37, 37))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jatm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcatm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari)
                    .addComponent(jLabel23))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(132, 196, 242));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "tabel penjualan"));

        tabel_jual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_jual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_jualMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_jual);

        jScrollPane3.setViewportView(jScrollPane4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1519, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel25.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtransaksiActionPerformed

      //kondisiAktif();
      
     // CariPelanggan();
      
        
        
            
     try {
             AutoID();
             kondisiAktif();
             jbarang.requestFocus(true);
         } catch (SQLException ex) {
             Logger.getLogger(transaksioffline.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_jtransaksiActionPerformed

    private void jinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinsertActionPerformed
        // TODO add your handling code here:
         TambahData();
        loadData();
        tampilkan();
    }//GEN-LAST:event_jinsertActionPerformed

    private void tabel_stokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_stokMouseClicked
        // TODO add your handling code here:
        int baris = tabel_stok.getSelectedRow();
        if (baris != -1) {
            jbarang.setText(tabel_stok.getValueAt(baris, 0).toString());
            jhargaawal.setText(tabel_stok.getValueAt(baris, 7).toString());
            jstok.setText(tabel_stok.getValueAt(baris, 8).toString());
        
        }
        
    }//GEN-LAST:event_tabel_stokMouseClicked

    private void jjmlhbeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jjmlhbeliKeyReleased
        // TODO add your handling code here:
        a = Integer.parseInt(jhargaawal.getText());
        b = Integer.parseInt(jjmlhbeli.getText());
       c=a*b;
        jhrgbrng.setText(String.valueOf(c));
        
    }//GEN-LAST:event_jjmlhbeliKeyReleased

    private void jcatmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcatmActionPerformed
        // TODO add your handling code here:
         int i=jcatm.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String nm=(String) jcatm.getSelectedItem();
           
             conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
             
            Statement s= con.createStatement();
            String sql = "Select idatm,bank,no_rekening from atm WHERE bank=?";
            com.mysql.jdbc.PreparedStatement p=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            p.setString(1, nm);
            ResultSet result=p.executeQuery();
            result.next();
            
           // jnmbarang.setText(result.getString("nama barang"));
            jatm.setText(result.getString("no_rekening"));
           // jjmlhpotong.setText(result.getString("jmlptg"));
           
            
            }catch(SQLException e){
           // System.out.println(e);        
           JOptionPane.showMessageDialog(null, e.getMessage());
         }
        
    }//GEN-LAST:event_jcatmActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
         tampilkan();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
       int jumlah = tabel_jual.getRowCount();
//int totalBiaya = 0;
int totalsemua =0 ;
//int jumlahpotongan = 0;
int jumlahpotongan=0;
//int jumlahBarang1=0;
int jumlahBarang=0;
int totalBiaya=0;
int totalBiaya1=0;
int hasil=0;
int jumlahpotongantotal ,jumlahBarang1, hargaBarang;

String harga;

c = Integer.parseInt(jjmlhpakaian.getText());
d = Integer.parseInt(jpotongan.getText());
e = Integer.parseInt(jbiayakrm.getText());
 
TableModel tabelModel;
tabelModel = tabel_jual.getModel();
       for (int i=0; i<jumlah; i++){
 //   jumlahBarang1 = jumlahBarang1 + (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    jumlahBarang1= Integer.parseInt(tabelModel.getValueAt(i, 5).toString());
    jumlahBarang= jumlahBarang + (Integer.parseInt(tabelModel.getValueAt(i, 5).toString()));
    hargaBarang = (Integer.parseInt(tabelModel.getValueAt(i, 6).toString()));
        if(jumlahBarang < c){
          //  totalBiaya=totalBiaya+(jumlahBarang*hargaBarang);
       totalBiaya=totalBiaya+hargaBarang;
        }else {
          //  hargaBarang=hargaBarang;
          jumlahpotongan= (d*jumlahBarang)  ;
            
           hasil=hasil+(hargaBarang);
           // totalBiaya=totalBiaya+(hasil);
        
        }
        
        
      //  JOptionPane.showMessageDialog(null, "harga"+hargaBarang );
      //  JOptionPane.showMessageDialog(null, "potongan"+jumlahpotongan);
       // JOptionPane.showMessageDialog(null, "total"+totalBiaya);
           
       }
       totalBiaya=totalBiaya+(hasil-jumlahpotongan)+e;
       
       
    jtotharga.setText(String.valueOf(totalBiaya));
    jdiskon.setText(String.valueOf(jumlahpotongan));
    jTextField1.setText(String.valueOf(jumlahBarang));
        
    }//GEN-LAST:event_btnhitungActionPerformed

    private void tabel_jualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_jualMouseClicked
        // TODO add your handling code here:
         int i=tabel_jual.getSelectedRow();
        
        if(i==-1)
        {
            return;
        }
        String kode=(String) tabel_jual.getValueAt(i, 0);        
               
        String kodebar=(String) tabel_jual.getValueAt(i, 3);
        String jml=(String) tabel_jual.getValueAt(i, 5);
        
        String sql1="Update barang Set jumlah=jumlah + ? where id_barang=?";
        String sql="Delete from penjualan where no_transaksi=? AND id_barang=?";
    try {        
    
         conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
            
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, jml);
            st.setString(2, kodebar);
            st.executeUpdate();
            st.close();
            
            com.mysql.jdbc.PreparedStatement st2=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            st2.setString(1, kode);
            st2.setString(2, kodebar);
            st2.executeUpdate();
            st2.close();
            
    }catch(SQLException e) {
        System.out.println(e);
        JOptionPane.showMessageDialog(null, e.getMessage());
    }finally{
        
        loadData();
        tampilkan();
    }
        
    }//GEN-LAST:event_tabel_jualMouseClicked

    private void btnmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmemberActionPerformed
        // TODO add your handling code here:
        ambilmember_online fDB = new ambilmember_online();
        fDB.fAB = this;
        fDB.setVisible(true);
        fDB.setResizable(false);
        
    }//GEN-LAST:event_btnmemberActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
         SimpleDateFormat date;
        date= new SimpleDateFormat("yyyy-MM-dd ");
       jLabel25.setText(date.format(jtgl.getDate()));
      
       updatebeli();
        simpan();
        print();
        
        
    }//GEN-LAST:event_btnprintActionPerformed

    private void jbarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbarangKeyReleased
        // TODO add your handling code here:
         DefaultTableModel tabelpegawai = new DefaultTableModel();
        tabelpegawai.addColumn("ID BARANG");
        tabelpegawai.addColumn("NAMA BARANG");
        tabelpegawai.addColumn("JENIS PAKAIAN");
        tabelpegawai.addColumn("UKURAN");
        tabelpegawai.addColumn("BRAND");
        tabelpegawai.addColumn("KATEGORI");
        tabelpegawai.addColumn("WARNA");
        tabelpegawai.addColumn("HARGA (RP)");
        tabelpegawai.addColumn("STOK");
        try {
            
           conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
         String sql = "select * from barang where id_barang like '%" + jbarang.getText() + "%'" ;
        Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
            
           
            
            
            while (res.next()) {
                tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)
                ,res.getString(6),res.getString(7),res.getString(8),res.getString(9)});
            }
           tabel_stok.setModel(tabelpegawai);
        } catch (Exception e) {
          
        }
        
    }//GEN-LAST:event_jbarangKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksionline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksionline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksionline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksionline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksionline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnmember;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jatm;
    private javax.swing.JTextField jbarang;
    private javax.swing.JTextField jbiayakrm;
    private javax.swing.JComboBox<String> jcatm;
    private javax.swing.JComboBox<String> jcnama;
    private javax.swing.JTextField jdiskon;
    private javax.swing.JTextField jhargaawal;
    private javax.swing.JTextField jhrgbrng;
    private javax.swing.JTextField jidmember;
    private javax.swing.JButton jinsert;
    private javax.swing.JTextField jjmlhbeli;
    private javax.swing.JTextField jjmlhpakaian;
    private javax.swing.JTextField jkirim;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jpotongan;
    private javax.swing.JButton jprint;
    private javax.swing.JTextField jrekbeli;
    private javax.swing.JTextField jstok;
    private com.toedter.calendar.JDateChooser jtgl;
    private javax.swing.JTextField jtingkatan;
    private javax.swing.JTextField jtotbayar;
    private javax.swing.JTextField jtotharga;
    private javax.swing.JButton jtransaksi;
    private javax.swing.JTextField lb_faktur;
    private javax.swing.JTable tabel_jual;
    private javax.swing.JTable tabel_stok;
    // End of variables declaration//GEN-END:variables

    

    private void loadData() {
        
         DefaultTableModel model = new DefaultTableModel();
         model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {  
            conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                
           // Connection c=ClassDB.getkoneksi();
            Statement s= con.createStatement();
            String sql="Select * from penjualan where no_transaksi='" + this.jhrgbrng.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o=new Object[6];
                o[0]=r.getString("no_transaksi");
                o[1]=r.getString("tgl_transaksi");               
                o[2]=r.getString("kd_barang");
                o[3]=r.getString("harga");
                o[4]=r.getString("jumlah");                
                o[5]=r.getString("totalharga");
                
                model.addRow(o);
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
        
    }

    private void kondisiAktif() {
         //To change body of generated methods, choose Tools | Templates.
         
          
        
        jbarang.setEnabled(true);
        jtgl.setEnabled(true);
       
        jjmlhbeli.setEnabled(true);
        
        
        jidmember.setEnabled(true);
        
        jkirim.setEnabled(true);
        jrekbeli.setEnabled(true);
        
        jtotharga.setEnabled(false);
        jtotbayar.setEnabled(true);
        btnhitung.setEnabled(true);
        
        jinsert.setEnabled(true);
        jButton1.setEnabled(true);
        jprint.setEnabled(true);
        jcatm.setEnabled(true);
        btncari.setEnabled(true);
        lb_faktur.setEnabled(true);
        
        btnmember.setEnabled(true);
         
    }

    private String AutoID() throws SQLException{
       
        
        
        
        String sql = "select max(no_transaksi) from penjualan";
        //"Select nofaktur as no from jual ORDER by nofaktur desc"
        //select max(no_transaksi) from penjualan
            String idPenjualan = "";
       try{
           
            conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
           
            Date date= new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = dateFormat.format(date);
            jtgl.setDate(date);
            SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd.MM.YYYY");
            String tanggal2 = dateFormat2.format(date);
            count ++;
          // String sqlTanggal = "SELECT no_transaksi FROM penjualan limit 1";
        // String sqlTanggal1 = "select max(no_transaksi) from penjualan"; 
       // resultSet = statement.executeQuery(sqlTanggal);
   //     while (resultSet.next()) {
         //     String data1 = resultSet.getString(1);
             
            //   count = Integer.valueOf(data1);
            //    count++;
                  
          // }
            
            idPenjualan = "LCTOL." + tanggal + "." + count ;
           // String sql = "INSERT INTO penjualan VALUES('"+ idPenjualan + "',' coba ',NOW(),0 )";
          // statement.executeQuery(sql);
            lb_faktur.setText(""+(idPenjualan));
                
       } catch (SQLException e){
       
           JOptionPane.showMessageDialog(null, "terjadi kesalahan"+ e.getMessage());
       
       }
      return idPenjualan;
    
   }

    private void tampilkan() {
         //To change body of generated methods, choose Tools | Templates.
          DefaultTableModel tabelpegawai = new DefaultTableModel();
        tabelpegawai.addColumn("NO TRANSAKSI");
        tabelpegawai.addColumn("TANGGAL");
        tabelpegawai.addColumn("ID MEMBER");
        tabelpegawai.addColumn("ID BARANG");
        tabelpegawai.addColumn("HARGA");
        tabelpegawai.addColumn("JUMLAH");
        tabelpegawai.addColumn("TOTAL HARGA");
        tabelpegawai.addColumn("TUJUAN");
        
        tabelpegawai.addColumn("REK TOKO");
        tabelpegawai.addColumn("REK BELI");
       
        
        try {
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        //String sql = "select * from penjualan where no_transaksi like '%" + jpenjualan.getText() +"%'";
        String sql = "select * from penjualan where no_transaksi='"+lb_faktur.getText()+"'AND idmember='"+jidmember.getText() + "'";
        Statement stat = con.createStatement();
        ResultSet res=stat.executeQuery(sql);
        while (res.next()){
            tabelpegawai.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4)
            ,res.getString(5),res.getString(6),res.getString(7),res.getString(8)
            ,res.getString(9),res.getString(10)});
        }
        tabel_jual.setModel(tabelpegawai);
        } catch(Exception e){
        
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
         
         
    }

    private void TambahData() {
        
        String no=this.lb_faktur.getText();
      String kode= this.jbarang.getText();
    java.util.Date tgl=(java.util.Date) this.jtgl.getDate();
    String member = this.jidmember.getText();
   
    String Harga=this.jhargaawal.getText();
    String Jml=this.jjmlhbeli.getText();
    String total=this.jhrgbrng.getText();
    String tujuan=this.jkirim.getText();
    
    String rek_toko=this.jatm.getText();
    String rek_pembeli=this.jrekbeli.getText();
    String nama_toko=(String) this.jcnama.getSelectedItem();
    
    

 try {
            String sql1="Select * from penjualan where no_transaksi='" + no + "' AND id_barang='" + kode +  "'";
           
             conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
            
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            ResultSet rs=st.executeQuery(sql1);
             if (rs.next())
            {
            String sql = "UPDATE penjualan Set jumlah=jumlah + ?,total_harga= total_harga + ? where no_transaksi='" + no + "' AND id_barang='" + kode + "'";
            com.mysql.jdbc.PreparedStatement p2=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            
            p2.setString(1, Jml);
            p2.setString(2, total);           
            p2.executeUpdate();
            p2.close();
            this.updatebarang(Jml, kode);
            
            }else{
            String sql = "Insert into penjualan values (?,?,?,?,?,?,?,?,?,?,?)";
            com.mysql.jdbc.PreparedStatement p=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            p.setString(1, no);
            p.setDate(2,  new java.sql.Date(tgl.getTime()));         
            p.setString(3, member);
            p.setString(4, kode);                        
            p.setString(5, Harga);                        
            p.setString(6, Jml);                        
            p.setString(7, total);            
            p.setString(8, tujuan);    
             
            p.setString(9, rek_toko); 
            p.setString(10, rek_pembeli); 
            p.setString(11, nama_toko);
            p.executeUpdate();
            p.close();
            this.updatebarang(Jml, kode);
            this.updatemember(tgl, member);
            
            }
        }catch(Exception e){
            System.out.println(e);
 JOptionPane.showMessageDialog(null, e.getMessage());           
        }
 
 finally{
            loadData();
            
        }    
        
    }

    private void kondisiawal() {
        
        jbarang.setEnabled(false);
        jpotongan.setEnabled(false);
        jjmlhpakaian.setEnabled(false);
        jatm.setEnabled(false);
        jtgl.setEnabled(false);
        jhargaawal.setEnabled(false);
        jjmlhbeli.setEnabled(false);
        jstok.setEnabled(false);
        jhrgbrng.setEnabled(false);
        jidmember.setEnabled(false);
        jnama.setEnabled(false);
        jkirim.setEnabled(false);
        jrekbeli.setEnabled(false);
        
        jtotharga.setEnabled(false);
        jtotbayar.setEnabled(false);
        btnhitung.setEnabled(false);
        
        jinsert.setEnabled(false);
        jButton1.setEnabled(false);
        jprint.setEnabled(false);
        jcatm.setEnabled(false);
        btncari.setEnabled(false);
        lb_faktur.setEnabled(false);
        jtingkatan.setEnabled(false);
        btnmember.setEnabled(false);
        jidmember.setEnabled(false);
    }

    private void updatebarang(String Jml, String kode) {
         //To change body of generated methods, choose Tools | Templates.
          String sql1="Update barang Set jumlah=jumlah - ? where id_barang=?";
    try {        
  
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, Jml);
            st.setString(2, kode);
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
        
    

         
    }

    private void loadcomatm() {
       
         try {        
        jcatm.removeAllItems();
        
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                    
        
            Statement s= con.createStatement();
            String sql="Select * from atm";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                jcatm.addItem(r.getString("bank"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        } 
        
    }

    private void CariPelanggan() {
        //To change body of generated methods, choose Tools | Templates.
       
    }
    
    private void auto_number(){
      /*
        try {
           
             conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                    
        
            Statement s= con.createStatement();
           
            ResultSet r=s.executeQuery(sql);
            String sql = "SELECT MAX(right (no_transaksi.2)) AS no FROM penjualan";
           
            while (r.next()){
                if (r.first() == false){
                    lb_faktur.setText("LCTOL001");
                } else{
                    r.last();
                    int auto_id = r.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int noLong = no.length();
                            for (int a = 0; a<3-noLong; a++){
                                no = "0" + no;
                            }
                            lb_faktur.setText("LCTOL" + no);
                }
            
            }
        
        } catch (Exception e) {
           // JOptionPane.showMessageDialog(this, "Error: \n" + e.toString(), "kesalahan" , JOptionPane.WARNING_MESSAGE);
           JOptionPane.showMessageDialog(null, e.getMessage());
        
        }
        
    */
    
    }

    void itemTerpilih() {
        //To change body of generated methods, choose Tools | Templates.
         ambilmember_online fDB = new ambilmember_online();
        fDB.fAB = this;
        jidmember.setText(idmember);
        
        jpotongan.setText(diskon);
        jjmlhpakaian.setText(jmlptong);
        jtingkatan.setText(tingkatan);
        jnama.setText(nama);
    }

    private void updatemember(Date tgl, String member) {
         //To change body of generated methods, choose Tools | Templates.
         String sql1="Update member Set tgl=  ? where idmember=?";
    try {        
  
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
      String sql2 = "SELECT * from member";
            Statement st2  =con.createStatement();
            ResultSet sr2 = st2.executeQuery(sql2);
            while(sr2.next()){
        String tanggal = sr2.getString(9);
        String[] tgl_trans =  tanggal.split("-");
        String sql3 = "Select idmember,sum(jumlah) as jml from penjualan where idmember='"+sr2.getString(1)+"' and date(tgl) between date('"+tanggal+"') and date('"+tgl_trans[0]+"-"+((Integer.valueOf(tgl_trans[1]))+1)+"-"+tgl_trans[2]+"')";
        Statement st3 = con.createStatement();
        ResultSet sr3 = st3.executeQuery(sql3);
        String[] tgl2 = (tgl.toString()).split("-");
        if((Integer.valueOf(tgl2[0])) > ((Integer.valueOf(tgl_trans[0]))) || ((Integer.valueOf(tgl2[1]))) > ((Integer.valueOf(tgl_trans[1]))+1) && ((Integer.valueOf(tgl2[2]))) >((Integer.valueOf(tgl_trans[2]))) ){
        while(sr2.next()){
            if((sr3.getString(7).equals("AGEN"))){
                if(sr3.getInt(2) < 7){
                    this.updatetingkatan("GROSIR", sr3.getString(1));
                }
            }
            if((sr3.getString(7).equals("DISTRIBUTOR"))){
                if(sr3.getInt(2) < 20){
                    this.updatetingkatan("AGEN", sr3.getString(1));
                }
            }
        }
        }
        }
       
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setDate(1, new java.sql.Date(tgl.getTime())); 
            st.setString(2, member);
            
           
         
            st.executeUpdate();
            st.close();
           
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
         
    }

    private void updatetingkatan(String grosir, String member) {
         //To change body of generated methods, choose Tools | Templates.
          String sql1="Update member Set tingkatan=  ? where idmember=?";
        
    try {        
  
        conek getCnn = new conek();
        
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        
            com.mysql.jdbc.PreparedStatement st=(com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql1);
            st.setString(1, tingkatan); 
            st.setString(2, member);
            
           
         
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
//        /System.out.println(e);
         JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }

    void itemtoko() {
         //To change body of generated methods, choose Tools | Templates.
          
    }

    private void loadcomtoko() {
        //To change body of generated methods, choose Tools | Templates.
        
         try {        
        jcnama.removeAllItems();
        
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
                    
        
            Statement s= con.createStatement();
            String sql="Select * from toko";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                jcnama.addItem(r.getString("nama"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        } 
    }

    private void print() {
        try {
           
           // Class.forName("com.mysql.jdbc.Driver");
           // con = DriverManager.getConnection("jdbc:mysql://localhost/toko");
         
            
       
           
             
            File file = new File("src/laporan/report5.jrxml");
            jasDes = JRXmlLoader.load(file);
            //penjualan.clear();
            
            String ttrans = (lb_faktur.getText());
            penjualan.put("no_transaksi", ttrans);
            
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, penjualan, con);
            JasperViewer.viewReport(jasPri, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            e.printStackTrace();
        } //To change body of generated methods, choose Tools | Templates.
    }

    private void simpan() {
         //To change body of generated methods, choose Tools | Templates.
         try {
        conek getCnn = new conek();
        con= null;
        con= (com.mysql.jdbc.Connection) getCnn.getConnection();
        String sql="insert into pembayaran values('"+lb_faktur.getText()
                +"','"+jidmember.getText()               
                +"','"+jtotharga.getText()
                +"','"+jtotbayar.getText()
                +"','"+jLabel23.getText()
                +"','"+jdiskon.getText()
                +"','"+jLabel25.getText()
                
                +"')";
        st=con.createStatement();
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Data sukses tersimpan");
        
      
        
        } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Data GAGAl");
            }
         
    }

    private void updatebeli() {
         //To change body of generated methods, choose Tools | Templates.
         
         
                try {
                     String sql="update member set tgl=? where idmember='"+jidmember.getText()+"'";
                
                     PreparedStatement st=con.prepareStatement(sql);
                //if(ok==0)
                {
                try
                    {
                        st.setString(1,jLabel25.getText());
                        
                        
                        
                        st.executeUpdate();
      
       
        //String sql="insert into pembayaran values('"+jpenjualan.getText()
                
       
        JOptionPane.showMessageDialog(null, "Data sukses tersimpan");
        
      
        
        } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Data GAGAl");
            }
        
                }   
    }catch (Exception a){}
         
    }

    
    
    
}
